### ISSUE TITLE
JSSAlertView only works on initial viewcontroller

### ISSUE THREAD

**Issue by jellehendriks007** [openstakes/JSSAlertView#29]
Dear all, 

I'm trying to embed JSSAlertView in my APP. On my first page (the initial viewcontroller) this seems to be working very smoothly. However on all other pages I can't. 

```
@IBAction func testbuttonn(sender: UIButton) {    
    JSSAlertView().show(self, title: "Standard alert", text: "A standard alert with some text looks like this", buttonText: "Yay")
}
```

Would be great if you can provide some help. Thanks!

**Comment by syky27** [comment]
Hi!

Can you provide more code please? 
What are you trying to do? Are you trying to fire up JSSAlertView from different ViewController than it is own in?

Thanks

**Comment by syky27** [comment]
Let me know what is this all about tho.
