### ISSUE TITLE
Create organisation for this repo & create pod

### ISSUE THREAD

**Issue by syky27** [openstakes/JSSAlertView#33]
Hi @stakes 

I would like to create organisation for this repo, it will make my work way easier, and I would also like to have organisation when creating pod.

When we figure out the correct name (don't) really care about it tho.

It is possible to transfer repo including forks stars watching to organisation according to github docs.

What do you think about it?

Thanks 
Syky.

**Comment by syky27** [comment]
And now when solving issue #30 I would love to create new repo for my test project where I debug the issue and do not want to create under my Github acc nor in my own Gitlab. :)

**Comment by stakes** [comment]
Here you go my man: https://github.com/openstakes/JSSAlertView

And thank you for getting involved and taking over managing this repo!

If you want to change the name of our "organization", just let me know. This one just kinda seemed like the easiest, but I'm in no way attached ;)
