### ISSUE TITLE
Unable to setup Travis

### ISSUE THREAD

**Issue by syky27** [openstakes/JSSAlertView#35]
Can you do that?

Or give me access?

Thanks

![screenshot 2016-04-04 17 22 59](https://cloud.githubusercontent.com/assets/2771802/14252994/10492db2-fa8a-11e5-9aa5-114ce45119e9.png)

**Comment by stakes** [comment]
@syky27 I just got to this, thanks! It's enabled and ready to go.

I can't figure out how the hell to add an admin to Travis CI or I would just add you.

Anyway, thanks again for all your help!
