### ISSUE TITLE
Invalid use of '()' to call a value of non-function type 'module<JSSAlertView>'

### ISSUE THREAD

**Issue by SimonTheEngineer** [openstakes/JSSAlertView#37]
Hi, I've installed the framework via Cocoapods but I'm receiving the above error message for the following code:

    override func viewDidLoad() {
        super.viewDidLoad()
        
        JSSAlertView().show(
            self, // the parent view controller of the alert
            title: "I'm an alert" // the alert's title
        )
    }

I have imported the framework as well in that ViewController

**Comment by syky27** [comment]
I will have a look at it right away

**Comment by syky27** [comment]
The error you are getting actually means like if show func would not be public tho.
But it is.
Can you run `pod update JSSAlertView` and show me the output?

**Comment by SimonTheEngineer** [comment]
Sure:

    Updating local specs repositories

    CocoaPods 1.0.0.beta.6 is available.
    To update use: `gem install cocoapods --pre`
    [!] This is a test version we'd love you to try.

    For more information see http://blog.cocoapods.org
    and the CHANGELOG for this version http://git.io/BaH8pQ.

    Analyzing dependencies
    Downloading dependencies
    Using JSSAlertView (1.0)
    Generating Pods project
    Integrating client project
    Sending stats
    Pod installation complete! There is 1 dependency from the Podfile and 1 total
    pod installed.

**Comment by syky27** [comment]
WOW!

you should have get this

```
╭─syky at aluminium in ~/Desktop/popover using ‹2.2.4›
╰─○ pod update JSSAlertView
Updating local specs repositories

CocoaPods 1.0.0.beta.6 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using JSSAlertView (1.0.1)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed
```

The newest version of the pod is 1.0.1, I am wondering if the change of the version system messed things up I will fire up a new version 1.1.1 and let you know it will be couple seconds. Than I am gonna need you to run that update command one more time.

**Comment by SimonTheEngineer** [comment]
Ok great

**Comment by syky27** [comment]
Can you please run it again and let me know how the output looked like?

**Comment by SimonTheEngineer** [comment]
Exactly the same output

    Using JSSAlertView (1.0)

**Comment by syky27** [comment]
How does your Podfile look like?

**Comment by SimonTheEngineer** [comment]
I was using

    platform :ios, '8.0'
    use_frameworks!

    target 'GCBeaconTest' do

      pod 'JSSAlertView'

    end

But I just tried using 

      pod 'JSSAlertView', '~> 1.1'

and got this output

    Updating local specs repositories

    CocoaPods 1.0.0.beta.6 is available.
    To update use: `gem install cocoapods --pre`
    [!] This is a test version we'd love you to try.

    For more information see http://blog.cocoapods.org
    and the CHANGELOG for this version http://git.io/BaH8pQ.

    Analyzing dependencies
    [!] Unable to satisfy the following requirements:

    - `JSSAlertView (~> 1.1)` required by `Podfile`

    Specs satisfying the `JSSAlertView (~> 1.1)` dependency were found, but they required a higher minimum deployment target.

**Comment by syky27** [comment]
hah, I know.... hmmmm is it possible for you to change 
This `platform :ios, '8.0'` to this: `platform :ios, '8.3'` or do you really need to support `8.0`?

**Comment by SimonTheEngineer** [comment]
I can change it if it's required, let me try that

**Comment by SimonTheEngineer** [comment]
Yeah that works now.

Any reason why it requires 8.3 though? I thought it would work for iOS 7+

**Comment by syky27** [comment]
Well, The `8.3` was stupid I changed back to `8.0` I actually have no idea where this mistake origins from.

So you can set your Podfile back to `8.0`.

About the iOS 7 Swift currently does not support compiling Frameworks for iOS 7.

So you can use JSSAlertView but you need to add it manually to project.

**Comment by SimonTheEngineer** [comment]
Ah ok, that's great, thanks for your help. Didn't expect a response so fast :+1:

**Comment by syky27** [comment]
Thank you for using JSSAlertView.
