### ISSUE TITLE
Tab Buttons still tappable when alert is shown

### ISSUE THREAD

**Issue by gearoidoceallaigh** [openstakes/JSSAlertView#40]
I use tab bar controller in my application and when the alert is displayed these remain tappable. Would it be possible to make the alert cover the entire screen?

Great library btw!

**Comment by syky27** [comment]
Well this is not actually hadeled very well right now, I can create workaround for this usecase in couple of days.... I plan on rewriting most of it in close future tho...

**Comment by macecchi** [comment]
Any updates about this?

**Comment by syky27** [comment]
Hi, just informing you that I have not forgotten about this, I plan on fixing this with some kind of hotfix, later this week...

Thanks.

**Comment by macecchi** [comment]
@syky27 I've modified JSSAlertView to be presented as a view controller, which I think is the correct approach. I can send a PR if you're interested :)

**Comment by syky27** [comment]
Go for it I'll check it out!

**Comment by syky27** [comment]
@gearoidoceallaigh please update to 1.1.5 version

Thanks goes to @macecchi for #42
