### ISSUE TITLE
How to make alert disappear automatically?

### ISSUE THREAD

**Issue by giuseppe19** [openstakes/JSSAlertView#41]
I'm trying to use your amazing library and make alert disappear automatically, but without success yet :/
Would it be possible?

Again, amazing job my friend!

**Comment by syky27** [comment]
Hi, 
   there is not internal API for it. I can add it if you like.

**Comment by giuseppe19** [comment]
It would be awesome, if I don't ask too much...

**Comment by syky27** [comment]
Hey buddy, it's done. Go ahead and run.

`pod update`

There is a new option for show, success, danger, warning, info `delay`.  Example:

```
JSSAlertView().show(
  self, // the parent view controller of the alert
  title: "I'm an alert", // the alert's title
  delay: 3 // time in secs
)
```

**Comment by giuseppe19** [comment]
Great! Thank you my friend!
Greetings, Giuseppe
