### ISSUE TITLE
i have a crash

### ISSUE THREAD

**Issue by huangboju** [openstakes/JSSAlertView#46]
```
 *** Assertion failure in void _UIPerformResizeOfTextViewForTextContainer(NSLayoutManager *, UIView<NSTextContainerView> *, NSTextContainer *, NSUInteger)(), /SourceCache/UIFoundation/UIFoundation-376.14/UIFoundation/TextSystem/NSLayoutManager_Private.m:1547
```

<img width="616" alt="2016-06-24 2 08 51" src="https://cloud.githubusercontent.com/assets/14818224/16329458/3f87b7ae-3a15-11e6-8023-8f43916578a2.png">

**Comment by syky27** [comment]
What Xcode and iOS SDK are you using? Thanks.

**Comment by huangboju** [comment]
Xcode version is 7.3.1 and simulator is iPhone5，system version is 8.4

**Comment by syky27** [comment]
Can you repeat this? Or did that happened only once?
