### ISSUE TITLE
Counting timer in alert

### ISSUE THREAD

**Issue by Xpressive** [openstakes/JSSAlertView#54]
How can i display a counting label in alert? Like in Tinder, for example, when you exceeded your likes/superlikes limit

**Comment by syky27** [comment]
JSSAlertView, doesn't support this functionality you would have to modify the code.

**Comment by Xpressive** [comment]
I can make pr, if you want this functionality. It looks and works nice ;)

**Comment by syky27** [comment]
Sure, it would be awesome.
